label intro:
    show kage neutral at left
    sakurako "Whoa!"
    sakurako "Holy smokes!"
    sakurako "With that big sloppy meteor shower from Agent Kitazoe, the first match of the new B-Rank War season is off to an explosive start!"
    pc "Wow...!"
    pc "So this is a rank war!"
    pc "I heard about them during orientation..."
    call suwa_intro
    narrator "At Border, all of the eligible B-Rank squads are split up into upper, middle, and lower groups depending on their official ranks. Then they do three- or four-way team battles within their group to try and win as many points as they can to climb the ranks. The squads at the very top even get the chance to try and take on A-Rank."
    pc "Still, seeing it live is way better compared to just hearing how it works."
    pc "B-Rank agents are on a whole other level!"
    narrator "Explosions tear through the map, debris flying everywhere as meteor bullets rain down. A few different video feeds show the agents in the battle as they react, running out of range or regrouping with their squadmates. A smaller window shows as an agent prepares a composite bullet of their own, and then the main feed lights up with another explosion."
    narrator "The action gets hard to follow even with the multiple camera angles as more explosions rock the rank war stage. Agents from all three squads weave through the dust and the debris, closing in on each other as their teammates let loose with their prepared shooter bullets."
    sakurako "Ouji Squad returns fire!!"
    show kage neutral at left
    sakurako "Kageura Squad must have been hoping to mow down the competition early with that gutsy barrage, but Ouji Squad and Azuma Squad hold them at bay!!"
    narrator "Another feed moves front and center as two other agents give chase to their opponents with their swords drawn. Yet another feed shows a sniper shoot from across the map and then it happens - the hit connects, and the main screen fills with smoke as the cornered agent bails out."
    sakurako "The meteors were a feint! Kageura Squad lands the first point as Agent Kaorai bails out after Agent Ema snipes him through the chaos!"
    sakurako "What an exciting first round already! The upper ranks really are B-Rank at its best!"
    pc "Wow!!"
    pc "B-rank, huh...?"
    pc "Only a few hundred more points to go until I join them..."
    
    pc "Yes!!"
    pc "Finally!!"
    pc "I finally made it to B-Rank!!!"
    pc "I spent so long slumming it in C-Rank that I still can't believe it's real. "
    pc "Like...me?"
    pc "An official agent!?"
    pc "All that hard work really paid off."
    pc "Okay!"
    pc "Next order of business..."
    narrator "No more being a free agent. It's time for you to join a squad so that you can be in the Rank Wars."
    narrator "Or...you could always form your own squad, but would you even be able to recruit enough people in time? "
    pc "I do have a whole month until the season starts..."
    pc "No, no, no!!!"
    pc "{i}What am I even thinking!?{/i}"
    pc "There's no way I could do that."
    pc "30 days isn't nearly enough time to find an operator and other combatants."
    narrator "Okay, no doubt about it. The best way for you to be a part of the next Rank War season is by joining a squad that has an open spot for someone new. Otherwise, you'll have to wait for another four months for the new season to start."
    narrator "And, if you want to get recruited by an established squad, you have to find a way to stand out."
    pc "My skills, my strategies..."
    pc "I can't fall behind if I want to get recruited."
    pc "Every little thing is gonna count."
    pc "Oh!"
    pc "I'll have to make the right connections, too!"
    pc "You can't recruit someone you don't know, right?"
    pc "Okay, [player.name]!"
    pc "You've got this!"
    narrator "You're still in the middle of psyching yourself up, fist pumps and all, when you hear people approaching from behind you. Which, pretty normal for a public hallway. But it had been empty for so long that it still catches you off guard."
    #???
    show ouji neutral at left
    ouji "Hey, Rookie!"
    pc "Ah-"
    #???
    show arafune neutral at right
    arafune "What are you mumbling about over there?"
    narrator "You turn around fast at the voices, finding yourself face to face with the two official agents who had snuck up on you."
    narrator "Even though I've never met them before, I know exactly who they are. "
    narrator "Arafune Tetsuji, action sniper. Captain of Arafune Squad, ranked 10th amongst the competitive B-Rank squads. Proficient with rifles, swords, and making baseball hats look cool."
    narrator "Ouji Kazuaki, tricky attacker and known eccentric. Captain of the 5th ranked Ouji Squad. Despite his smiley demeanor, he's a ruthless attacker with a versatile trigger set. You even saw one of his brutal takedowns in the first Rank War you ever watched."
    pc "Ah...!"
    pc "Wait, you heard that?"
    ouji "Well, Arafunny said 'mumbling', but you were actually talking pretty loudly."
    ouji "Haha, how embarrassing~"
    pc "Ah."
    pc "I'm ruined."
    narrator "Either of their squads would be perfect if they'd have you. Ouji's squad has always been solidly placed in the upper ranks, and everyone knows Arafune's squad is tough competition in the middle ranks. Not to mention both captains are insanely talented on their own."
    pc "...and here I am, putting my foot in my mouth..."
    ouji "Oh?"
    ouji "You sound flexible!"
    arafune "Hey."
    arafune "Knock it off, Ouji."
    ouji "Boooo."
    pc "They seem like good friends..."
    narrator "The two of them bicker with each other, making faces and throwing elbows. It looks like this happens a lot, or at least enough for them to be comfortable doing it in front of a third party. Honestly, you're worried that they forgot you were there in the first place, but Arafune seems to remember and turns to you before you can make an escape."
    arafune "Wait, sorry. I don't think we've met before."
    pc "Oh, you're right!"
    pc "My name's [player.name]! I'm in my third year of high school and I just got promoted to B-Rank!"
    pc "It's nice to meet you!"
    arafune "...pft."
    ouji "Hahaha."
    arafune "We're all the same age, then."
    arafune "Arafune Tetsuji."
    arafune "This guy's Ouji."
    ouji "Hello~"
    arafune "Anyway. Were you headed for the solo lounge?"
    pc "Huh?"
    pc "Oh, yeah!"
    pc "I figured I'd go take a peek while I'm free. I'm scoping out all of my potential prospects."
    arafune "Potential prospects?"
    ouji "Sounds interesting!"
    ouji "Okay. I've decided."
    ouji "Come with us, little Rookie."
    ouji "Arafunny and I'll take you to see what prospects you really have."
    narrator "Before you can say anything, Ouji's already walking off towards the solo lounge. Arafune just shrugs at you before he follows behind him, and it'd be rude for you to run away now since you're going in the same direction, so it's not like you really have a choice but to join."
    narrator "While you walk, the three of you make small talk. Ouji and Arafune pepper you with questions about your plans now that you've been promoted, and so naturally you spill your guts. It's not like it's a secret you want to join someone's squad, and with two top contenders right here, it makes sense to try and feel them out."
    arafune "Oh, so that's what you meant by prospects."
    arafune "You really think it's gonna be that easy to get recruited by a squad, huh?"
    ouji "Haha, don't just go and dash their dreams like that, Arafunny."
    ouji "Even if they're not good enough to get recruited by anyone, you're not supposed to just say it."
    pc "Hey! You don't even know that I'm not any good."
    arafune "..."
    ouji "..."
    pc "..."
    ouji "So, you're not any good."
    pc "I didn't mean it like that!"
    arafune "You're definitely not going to get recruited with that kind of attitude."
    narrator "Arafune and Ouji take turns making jokes at your expense as the three of you venture further into the lounge. You're just about to defend yourself when their attention turns elsewhere. "
    #???
    murakami "Arafune! Ouji!"
    #???
    kurauchi "What took you guys so long?"
    #???
    kurauchi "...Oh?"
    #???
    kage "When the hell did you two go and pick up a stray, huh?"
    arafune "Just now. We found them by the vending machines."
    ouji "They were crying about how they're not any good."
    pc "I wasn't crying..."
    ouji "This poor little puppy was crying so much that Arafunny and I took them under our wings and brought them here."
    narrator "You insist that you weren't crying at all, turning to the rest of the group to plead your case. It's only then that it really clicks exactly who you're talking to. You're so caught off guard that you barely even register their introductions as your own brain takes over, everything you know about them flashing past your eyes as they talk."
    narrator "Murakami Kou. Border's #4 attacker and the ace of 9th ranked Suzunari First. A genius attacker who's as good with his shield as he is with his sword."
    narrator "Kageura Masato. Captain of the former A-Rank Kageura Squad and currently ranked third in the B-Ranks. You've heard his personality is as mean as his mantis."
    narrator "Kurauchi Kazuki. Ouji Squad's righthand man and a competent shooter. His center part is so perfect it's a little intimidating."
    narrator "Basically? They're the very people you need to impress. The people who could make your dreams come true."
    murakami "It's nice to meet you."
    kurauchi "Likewise."
    pc "Ah, yeah. Thanks. Me, too."
    pc "You too?"
    pc "What I mean is, um, you know. It's nice to meet you all."
    pc "Uh...officially."
    ouji "Is your foot your favorite food? You're eating so much of it today~"
    kurauchi "I'm so sorry about him."
    ouji "Rude. Don't apologize for me."
    ouji "We're having fun! Aren't we, Rookie?"
    pc "Uh..."
    ouji "Oh, right! Listen to this."
    narrator "In his own way, Ouji tells the others all about your big plans to get recruited and join in on the Rank Wars. The way he says it is a little...unique. But, it gets the job done. Your dignity is still mostly intact when he's done."
    murakami "Ohhh, I see."
    murakami "So you're looking to join a squad now that you're B-Rank?"
    murakami "Congratulations on your promotion, by the way."
    pc "Thanks!"
    kage "Tsk."
    kage "Well, my squad doesn't have room for any newly promoted weaklings."
    kage "Go ride someone else's coattails."
    arafune "Come on, dude. Don't be like that."
    murakami "Play nice."
    ouji "No, no. Kage-kun's onto something. He's telling them to join a squad that sucks, right?"
    kurauchi "Ouji..."
    ouji "Hmm...who's hanging around here that has a squad that sucks?"
    narrator "Ouji's eyes land on his victim...er, target, and he immediately starts waving his arms over his head to catch their attention."
    ouji "Ah!"
    ouji "Suwa-san! Suwa-san, over here!"
    arafune "That's so cold..."
    kurauchi "It's rude, is what it is."
    ouji "Haha, he won't know if no one tells him."
    narrator "Arafune and Ouji both laugh at that, though Arafune at least looks like he's trying to hide it."
    ouji "Suwaaaa-sannnnnn!"

    ouji "Not so fast, Suwa-san."
    ouji "This little puppy still has their milk teeth. You have to train them first."
    suwa "What the hell does that even mean?"
    kurauchi "It's best if you don't question it."
    ouji "Rookie, you want to join a strong team, right?"
    ouji "Even Suwa-san's squad'll do, right?"
    suwa "Hang on-"
    ouji "So, how about this?"
    ouji "You go work really, really hard so that you're not terrible anymore."
    pc "Uh, I never said I was terrible..."
    ouji "There's 30 days until the new season starts, isn't there?"
    ouji "Go become a really strong puppy and then maybe one of us will adopt you."
    show arafune neutral at right
    arafune "Don't just decide that for us."
    murakami "I mean, if Kuruma-senpai is okay with it..."
    ouji "There, see? Everyone agrees."
    kage "I didn't agree to shit."
    ouji "Everyone agrees~"
    ouji "30 days, Rookie."
    pc "Okay...!"
    pc "Deal!"
    narrator "If they're really willing to offer, then this is a bet you're willing to take. 30 days might not be enough time to form a whole new squad from scratch, but it's definitely enough time to hone your skills so that you can catch the eye of one of these five squads."
    narrator "Although the method might have been different in your head, impressing a squad enough to get recruited was always the plan from the start! And with some strong squads already keeping you in mind, it just makes you want to work that much harder."
    narrator "Afterall, now that everything's coming together...it's only a matter of time..."
    pc "B-Rank Wars, here I come!"
    

label suwa_intro:
    scene bg hallway
    show suwa neutral at left
    suwa "I heard you!"
    suwa "Quit your yapping, Ouji."
    narrator "An older man with bleached hair stomps his way across the lounge right towards your group. You recognize him instantly, too."
    narrator "Suwa Koutarou. Captain of B-Rank 12's Suwa Squad and dual wielder of shotguns. You've never seen him at Border without his cigarette, but you've also never actually seen him smoke."
    suwa "Hah?"
    suwa "Who's this?"
    narrator "Suwa frowns at the lot of you, grinding the butt of a cigarette between his teeth as his eyes pass over each of you in turn."
    suwa "I swear you teenaged hellions grow in number every day..."
    show ouji neutral at right
    ouji "Haha, I knew we could count on Suwa-san."
    suwa "For what?"
    suwa "That's suspicious."
    suwa "What're y'all plotting over here?"
    murakami "[player.name]'s looking for a squad to join. They just got promoted to B-Rank."
    suwa "Yeah?"
    suwa "And you guys thought to foist them off on me?"
    narrator "Suwa eyes the other teens suspiciously before he turns his gaze to you."
    suwa "You [player.name]?"
    narrator "He looks you up and down, clearly sizing you up. You're in your trion body without any visible weapons, though, so you don't really know how he's sizing you up in the first place. Still, you straighten up your back reflexively. You know...to make a good impression and all."
    suwa "Well...I guess I could entertain the idea of a third combatant."
    hide suwa
    return